name: PR Terraform Plan
on:
  pull_request:
    branches: [ main ]
env:
  TF_WORKING_DIR: './tf'
  ARM_CLIENT_ID: ${{ secrets.SPN_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.SPN_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.SPN_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SPN_SUBSCRIPTION_ID }}
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: ./.github/actions/authentication
        with:
          client_id: ${{ secrets.SPN_CLIENT_ID }}
          client_secret: ${{ secrets.SPN_CLIENT_SECRET }}
          tenant_id: ${{ secrets.SPN_TENANT_ID }}
          subscription_id: ${{ secrets.SPN_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~> 1.8"

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init \
            -backend-config="key=backend_dev.tfstate"

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -no-color -detailed-exitcode || true

      - name: Comment Terraform Plan
        if: always()
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: terraform plan
          message: |
            ```terraform
            ${{ steps.plan.outputs.stdout }}
            ```